# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import racing_pb2 as racing__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in racing_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RacingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinGame = channel.unary_unary(
                '/racing.RacingService/JoinGame',
                request_serializer=racing__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=racing__pb2.JoinGameResponse.FromString,
                _registered_method=True)
        self.GetGameState = channel.unary_unary(
                '/racing.RacingService/GetGameState',
                request_serializer=racing__pb2.GetGameStateRequest.SerializeToString,
                response_deserializer=racing__pb2.GameState.FromString,
                _registered_method=True)
        self.RollDice = channel.unary_unary(
                '/racing.RacingService/RollDice',
                request_serializer=racing__pb2.RollDiceRequest.SerializeToString,
                response_deserializer=racing__pb2.RollDiceResponse.FromString,
                _registered_method=True)
        self.LeaveGame = channel.unary_unary(
                '/racing.RacingService/LeaveGame',
                request_serializer=racing__pb2.LeaveGameRequest.SerializeToString,
                response_deserializer=racing__pb2.LeaveGameResponse.FromString,
                _registered_method=True)


class RacingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RollDice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RacingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=racing__pb2.JoinGameRequest.FromString,
                    response_serializer=racing__pb2.JoinGameResponse.SerializeToString,
            ),
            'GetGameState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameState,
                    request_deserializer=racing__pb2.GetGameStateRequest.FromString,
                    response_serializer=racing__pb2.GameState.SerializeToString,
            ),
            'RollDice': grpc.unary_unary_rpc_method_handler(
                    servicer.RollDice,
                    request_deserializer=racing__pb2.RollDiceRequest.FromString,
                    response_serializer=racing__pb2.RollDiceResponse.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=racing__pb2.LeaveGameRequest.FromString,
                    response_serializer=racing__pb2.LeaveGameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'racing.RacingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('racing.RacingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RacingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/racing.RacingService/JoinGame',
            racing__pb2.JoinGameRequest.SerializeToString,
            racing__pb2.JoinGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/racing.RacingService/GetGameState',
            racing__pb2.GetGameStateRequest.SerializeToString,
            racing__pb2.GameState.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RollDice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/racing.RacingService/RollDice',
            racing__pb2.RollDiceRequest.SerializeToString,
            racing__pb2.RollDiceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/racing.RacingService/LeaveGame',
            racing__pb2.LeaveGameRequest.SerializeToString,
            racing__pb2.LeaveGameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
