# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: racing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'racing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cracing.proto\x12\x06racing\"4\n\x06Player\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08position\x18\x03 \x01(\x05\"\xb4\x01\n\tGameState\x12\"\n\x06status\x18\x01 \x01(\x0e\x32\x12.racing.GameStatus\x12\x1f\n\x07players\x18\x02 \x03(\x0b\x32\x0e.racing.Player\x12\x14\n\x0c\x63urrent_turn\x18\x03 \x01(\x05\x12\x0e\n\x06winner\x18\x04 \x01(\x05\x12\x13\n\x0bturn_number\x18\x05 \x01(\x05\x12\x11\n\tlast_dice\x18\x06 \x01(\x05\x12\x14\n\x0ctrack_length\x18\x07 \x01(\x05\"\x1f\n\x0fJoinGameRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"V\n\x10JoinGameResponse\x12\x11\n\tplayer_id\x18\x01 \x01(\x05\x12\r\n\x05token\x18\x02 \x01(\t\x12 \n\x05state\x18\x03 \x01(\x0b\x32\x11.racing.GameState\"$\n\x13GetGameStateRequest\x12\r\n\x05token\x18\x01 \x01(\t\" \n\x0fRollDiceRequest\x12\r\n\x05token\x18\x01 \x01(\t\"B\n\x10RollDiceResponse\x12\x0c\n\x04\x64ice\x18\x01 \x01(\x05\x12 \n\x05state\x18\x02 \x01(\x0b\x32\x11.racing.GameState\"!\n\x10LeaveGameRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\x13\n\x11LeaveGameResponse*Q\n\nGameStatus\x12\x1b\n\x17GAME_STATUS_UNSPECIFIED\x10\x00\x12\x0b\n\x07WAITING\x10\x01\x12\x0b\n\x07RUNNING\x10\x02\x12\x0c\n\x08\x46INISHED\x10\x03\x32\x8f\x02\n\rRacingService\x12=\n\x08JoinGame\x12\x17.racing.JoinGameRequest\x1a\x18.racing.JoinGameResponse\x12>\n\x0cGetGameState\x12\x1b.racing.GetGameStateRequest\x1a\x11.racing.GameState\x12=\n\x08RollDice\x12\x17.racing.RollDiceRequest\x1a\x18.racing.RollDiceResponse\x12@\n\tLeaveGame\x12\x18.racing.LeaveGameRequest\x1a\x19.racing.LeaveGameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'racing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTATUS']._serialized_start=578
  _globals['_GAMESTATUS']._serialized_end=659
  _globals['_PLAYER']._serialized_start=24
  _globals['_PLAYER']._serialized_end=76
  _globals['_GAMESTATE']._serialized_start=79
  _globals['_GAMESTATE']._serialized_end=259
  _globals['_JOINGAMEREQUEST']._serialized_start=261
  _globals['_JOINGAMEREQUEST']._serialized_end=292
  _globals['_JOINGAMERESPONSE']._serialized_start=294
  _globals['_JOINGAMERESPONSE']._serialized_end=380
  _globals['_GETGAMESTATEREQUEST']._serialized_start=382
  _globals['_GETGAMESTATEREQUEST']._serialized_end=418
  _globals['_ROLLDICEREQUEST']._serialized_start=420
  _globals['_ROLLDICEREQUEST']._serialized_end=452
  _globals['_ROLLDICERESPONSE']._serialized_start=454
  _globals['_ROLLDICERESPONSE']._serialized_end=520
  _globals['_LEAVEGAMEREQUEST']._serialized_start=522
  _globals['_LEAVEGAMEREQUEST']._serialized_end=555
  _globals['_LEAVEGAMERESPONSE']._serialized_start=557
  _globals['_LEAVEGAMERESPONSE']._serialized_end=576
  _globals['_RACINGSERVICE']._serialized_start=662
  _globals['_RACINGSERVICE']._serialized_end=933
# @@protoc_insertion_point(module_scope)
